# Generated by Django 2.1.7 on 2019-05-17 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employoapp', '0002_auto_20190517_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='phone_number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='employer',
            name='phone_number',
            field=models.CharField(max_length=10),
        ),
    ]
