# Generated by Django 2.1.7 on 2019-05-17 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employoapp', '0004_employer_designation'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='about',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='employer',
            name='about',
            field=models.TextField(blank=True),
        ),
    ]
