# Generated by Django 2.1.7 on 2019-05-18 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employoapp', '0005_auto_20190517_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='jobs',
            field=models.ManyToManyField(blank=True, related_name='employee_jobs_set', to='employoapp.Jobs'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='resume',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='employer',
            name='jobs',
            field=models.ManyToManyField(blank=True, related_name='employer_jobs_set', to='employoapp.Jobs'),
        ),
    ]
