# Generated by Django 2.1.7 on 2019-05-18 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employoapp', '0006_auto_20190518_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='resume',
            field=models.FileField(blank=True, upload_to='documents/%Y/%m/%d'),
        ),
    ]
