# Generated by Django 2.1.7 on 2019-05-18 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employoapp', '0008_auto_20190518_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='resume',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
