# Generated by Django 2.1.7 on 2019-05-19 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employoapp', '0010_jobfiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='job',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='employoapp.Jobs'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='employee',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='employoapp.Employee'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='skill',
            field=models.CharField(max_length=50),
        ),
    ]
