# Generated by Django 2.1.7 on 2019-05-19 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employoapp', '0011_auto_20190519_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employoapp.Jobs'),
        ),
    ]
