# Generated by Django 2.1.7 on 2019-05-19 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employoapp', '0012_auto_20190519_2055'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=50)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employoapp.Jobs')),
            ],
        ),
        migrations.RemoveField(
            model_name='skill',
            name='job',
        ),
    ]
