# Generated by Django 2.1.7 on 2019-05-19 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employoapp', '0013_auto_20190519_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='jobs',
            field=models.ManyToManyField(blank=True, null=True, related_name='employee_jobs_set', to='employoapp.Jobs'),
        ),
        migrations.AlterField(
            model_name='jobskill',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employoapp.Jobs'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employoapp.Employee'),
        ),
    ]
