# Generated by Django 2.1.7 on 2019-05-19 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employoapp', '0014_auto_20190519_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='company',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='employee',
            name='jobs',
            field=models.ManyToManyField(related_name='employee_jobs_set', to='employoapp.Jobs'),
        ),
    ]
