# Generated by Django 2.1.7 on 2019-05-19 16:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employoapp', '0015_auto_20190519_2141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobs',
            name='employer',
        ),
        migrations.AddField(
            model_name='jobs',
            name='employer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
