# Generated by Django 2.1.7 on 2019-05-21 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employoapp', '0016_auto_20190519_2152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobskill',
            name='job',
        ),
        migrations.AddField(
            model_name='jobskill',
            name='job',
            field=models.ManyToManyField(related_name='jobs_skill_set', to='employoapp.Jobs'),
        ),
    ]
