# Generated by Django 2.1.7 on 2019-05-21 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employoapp', '0017_auto_20190521_1146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobskill',
            name='job',
        ),
        migrations.AddField(
            model_name='jobskill',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employoapp.Jobs'),
        ),
    ]
