# Generated by Django 2.1.7 on 2019-05-27 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employoapp', '0019_auto_20190527_1201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobfiles',
            name='job',
        ),
        migrations.AddField(
            model_name='jobfiles',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employoapp.Jobs'),
        ),
    ]
