# Generated by Django 2.1.7 on 2019-05-27 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employoapp', '0020_auto_20190527_1202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobfiles',
            name='job',
        ),
        migrations.AddField(
            model_name='jobs',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.DeleteModel(
            name='JobFiles',
        ),
    ]
